//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyKicks {
    
    
    public partial class UploadShoeImages {
        
        /// <summary>
        /// afuImages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.AjaxFileUpload afuImages;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Jones.Isiah.Chapter17.MasterPage Master {
            get {
                return ((Jones.Isiah.Chapter17.MasterPage)(base.Master));
            }
        }
    }
}
